[build]
  command = "npm run build"
  # The publish directory is relative to the 'base' directory.
  publish = "dist"
  base = "frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200