# filepath: c:\Users\prosl\Desktop\beast-terminal\beast-terminal\netlify.toml
[build]
  command = "npm run build"
  publish = "frontend/dist"
  base = "frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200